-- Update Supabase types to include the new user_challenge_calendar_days table
-- This migration should be run after the main refactor migration

-- The types will be automatically generated by Supabase CLI
-- This file serves as a placeholder to ensure proper migration order 