-- Insert auth translation strings for both English and Polish
INSERT INTO ui_strings (string_key, value, language_id, category) VALUES 
-- English strings
('auth_welcome', 'Welcome to IguanaFlow', 'en', 'auth'),
('auth_signin', 'Sign In', 'en', 'auth'),
('auth_signup', 'Sign Up', 'en', 'auth'),
('auth_email', 'Email', 'en', 'auth'),
('auth_password', 'Password', 'en', 'auth'),
('auth_username', 'Username', 'en', 'auth'),
('auth_confirm_password', 'Confirm Password', 'en', 'auth'),
('auth_enter_email', 'Enter your email', 'en', 'auth'),
('auth_enter_password', 'Enter your password', 'en', 'auth'),
('auth_choose_username', 'Choose a username', 'en', 'auth'),
('auth_create_password', 'Create a password', 'en', 'auth'),
('auth_confirm_password_placeholder', 'Confirm your password', 'en', 'auth'),
('auth_signing_in', 'Signing in...', 'en', 'auth'),
('auth_creating_account', 'Creating account...', 'en', 'auth'),
('auth_create_account', 'Create Account', 'en', 'auth'),
('auth_welcome_back', 'Welcome back!', 'en', 'auth'),
('auth_signin_success', 'You have been successfully signed in.', 'en', 'auth'),
('auth_signin_failed', 'Sign in failed', 'en', 'auth'),
('auth_check_credentials', 'Please check your credentials and try again.', 'en', 'auth'),
('auth_password_mismatch', 'Password mismatch', 'en', 'auth'),
('auth_passwords_no_match', 'Passwords do not match. Please try again.', 'en', 'auth'),
('auth_account_created', 'Account created!', 'en', 'auth'),
('auth_verify_email', 'Please check your email to verify your account.', 'en', 'auth'),
('auth_signup_failed', 'Sign up failed', 'en', 'auth'),
('auth_try_again', 'Please try again.', 'en', 'auth'),

-- Polish strings
('auth_welcome', 'Witamy w IguanaFlow', 'pl', 'auth'),
('auth_signin', 'Zaloguj się', 'pl', 'auth'),
('auth_signup', 'Zarejestruj się', 'pl', 'auth'),
('auth_email', 'Email', 'pl', 'auth'),
('auth_password', 'Hasło', 'pl', 'auth'),
('auth_username', 'Nazwa użytkownika', 'pl', 'auth'),
('auth_confirm_password', 'Potwierdź hasło', 'pl', 'auth'),
('auth_enter_email', 'Wprowadź swój email', 'pl', 'auth'),
('auth_enter_password', 'Wprowadź swoje hasło', 'pl', 'auth'),
('auth_choose_username', 'Wybierz nazwę użytkownika', 'pl', 'auth'),
('auth_create_password', 'Utwórz hasło', 'pl', 'auth'),
('auth_confirm_password_placeholder', 'Potwierdź swoje hasło', 'pl', 'auth'),
('auth_signing_in', 'Logowanie...', 'pl', 'auth'),
('auth_creating_account', 'Tworzenie konta...', 'pl', 'auth'),
('auth_create_account', 'Utwórz konto', 'pl', 'auth'),
('auth_welcome_back', 'Witamy z powrotem!', 'pl', 'auth'),
('auth_signin_success', 'Zostałeś pomyślnie zalogowany.', 'pl', 'auth'),
('auth_signin_failed', 'Logowanie nieudane', 'pl', 'auth'),
('auth_check_credentials', 'Sprawdź swoje dane logowania i spróbuj ponownie.', 'pl', 'auth'),
('auth_password_mismatch', 'Hasła nie pasują', 'pl', 'auth'),
('auth_passwords_no_match', 'Hasła nie pasują. Spróbuj ponownie.', 'pl', 'auth'),
('auth_account_created', 'Konto zostało utworzone!', 'pl', 'auth'),
('auth_verify_email', 'Sprawdź swój email, aby zweryfikować konto.', 'pl', 'auth'),
('auth_signup_failed', 'Rejestracja nieudana', 'pl', 'auth'),
('auth_try_again', 'Spróbuj ponownie.', 'pl', 'auth');