-- Add UI strings for library page
INSERT INTO ui_strings (language_id, string_key, value, category) VALUES
('en', 'library.title', 'Figure Library', 'library'),
('en', 'library.subtitle', 'Explore and master aerial figures across different disciplines', 'library'),
('en', 'library.add_exercise', 'Add Exercise', 'library'),
('en', 'library.search_placeholder', 'Search figures...', 'library'),
('en', 'library.filters', 'Filters', 'library'),
('en', 'library.category', 'Category', 'library'),
('en', 'library.level', 'Level', 'library'),
('en', 'library.type', 'Type', 'library'),
('en', 'library.tags', 'Tags', 'library'),
('en', 'library.progress_status', 'Progress Status', 'library'),
('en', 'library.no_exercises', 'No exercises found matching your criteria.', 'library'),
('en', 'library.loading', 'Loading exercises...', 'library'),
('en', 'library.view_details', 'View Details', 'library'),
('en', 'library.delete_exercise', 'Delete Exercise', 'library'),
('en', 'library.delete_confirm', 'Are you sure you want to delete "{name}"? This action cannot be undone.', 'library'),
('en', 'library.success_deleted', 'Exercise deleted successfully', 'library'),
('en', 'library.error_delete', 'Failed to delete exercise', 'library'),
('en', 'library.error_load', 'Failed to load exercises', 'library'),
('en', 'library.no_description', 'No description available', 'library'),

-- Add UI strings for exercises/figures
('en', 'exercises.difficulty.beginner', 'Beginner', 'exercises'),
('en', 'exercises.difficulty.intermediate', 'Intermediate', 'exercises'),
('en', 'exercises.difficulty.advanced', 'Advanced', 'exercises'),
('en', 'exercises.difficulty.expert', 'Expert', 'exercises'),
('en', 'exercises.category.all', 'All', 'exercises'),
('en', 'exercises.category.silks', 'Silks', 'exercises'),
('en', 'exercises.category.hoop', 'Hoop', 'exercises'),
('en', 'exercises.category.pole', 'Pole', 'exercises'),
('en', 'exercises.category.straps', 'Straps', 'exercises'),
('en', 'exercises.type.all', 'All', 'exercises'),
('en', 'exercises.type.single_figure', 'Single Figure', 'exercises'),
('en', 'exercises.type.combo', 'Combo', 'exercises'),
('en', 'exercises.status.all', 'All', 'exercises'),
('en', 'exercises.status.completed', 'Completed', 'exercises'),
('en', 'exercises.status.for_later', 'For Later', 'exercises'),
('en', 'exercises.status.failed', 'Failed', 'exercises'),
('en', 'exercises.status.not_tried', 'Not Tried', 'exercises');